@startuml

@startsalt
{
{T
+ projec
++ assets
+++ dice
++++ dice-1.png
++++ ...
++++ dice-6.png
+++ help
++++ help_Dice_'Normal'.txt
++++...
++++ help_Piece.Piecewise.txt
++ Diagrams
+++ Files.puml
+++ ...
+++ Files.svg
+++ ...
++ DraggablePoint.py
++ LabelSpinbox.py
++ LaTeXformulaimage.py
++ controller.py
++ Piecewise.py
++ piecewisecubicsplines.py
++ PiecewiseGraph.py
++ README.md
++ requirements.txt
}
}
@endsalt

@enduml