@startuml

@startsalt
{
{T
+ projec
++ assets
+++ dice
++++ dice-1.png
++++ ...
++++ dice-6.png
+++ help
++++ help_Dice_'Normal'.txt
++++...
++++ help_Piece.Piecewise.txt
++ Diagrams
+++ Files.puml
+++ ...
+++ Files.svg
+++ ...
++ controller.py
++ draggablePoint.py
++ fittingFunctions.py
++ helperWidgets.py
++ LaTeXFormulaImage.py
++ models.py
++ README.md
++ requirements.txt
++ view.py
++ widgets.py
}
}
@endsalt

@enduml